// TermsOfService.jsx — the /terms page.
//
// COUNSEL REVIEW REQUIRED: this copy was drafted in-house and has not been
// reviewed by an attorney. The bracketed placeholders ([LEGAL ENTITY NAME],
// [CONTACT EMAIL], [GOVERNING JURISDICTION]) are pending facts from the
// owner and MUST be filled in before public launch. Bump TERMS_VERSION in
// src/constants/legal.js whenever this document materially changes.

import React from 'react';
import LegalPageLayout from './LegalPageLayout';

const TermsOfService = () => (
  <LegalPageLayout title="Terms of Service" lastUpdated="June 9, 2026">
    <h2>Acceptance of These Terms</h2>
    <p>
      These Terms of Service ("Terms") are an agreement between you and
      [LEGAL ENTITY NAME] ("SEVA", "we", "us", or "our") governing your use
      of the SEVA web application and related services (the "Service"). By
      creating an account or using the Service, you confirm that you are at
      least 13 years old and that you accept these Terms and our{' '}
      <a href="/privacy">Privacy Policy</a>. If you are under 18, you should
      review these Terms with a parent or guardian. If you do not agree, do
      not use the Service.
    </p>

    <h2>The Service</h2>
    <p>
      SEVA provides digital SAT preparation tools, including practice
      questions, full-length practice tests, diagnostic analysis,
      personalized study plans, and an AI-powered tutor. The Service is a
      study aid: practice scores, score projections, and diagnostic
      insights are estimates based on your practice work and do not
      guarantee any particular result on the actual SAT. We may add,
      change, or remove features of the Service at any time.
    </p>

    <h2>Accounts</h2>
    <p>
      You need an account to use the Service. You agree to provide accurate
      information at signup, to keep your password confidential, and to be
      responsible for all activity under your account. Notify us at
      [CONTACT EMAIL] if you believe your account has been accessed without
      authorization. Accounts are personal: one account per person, and you
      may not sell, transfer, or share your account.
    </p>

    <h2>Acceptable Use</h2>
    <p>When using the Service, you agree not to:</p>
    <ul>
      <li>
        Copy, scrape, redistribute, or resell practice questions,
        explanations, study plans, or any other content from the Service.
      </li>
      <li>
        Attempt to probe, disrupt, or gain unauthorized access to the
        Service, other users' accounts, or the systems it runs on.
      </li>
      <li>
        Use the AI tutor to generate content unrelated to SAT preparation,
        or attempt to misuse it to produce harmful, unlawful, or abusive
        output.
      </li>
      <li>
        Use automated tools (bots, scripts, crawlers) to access the Service
        except as permitted by us in writing.
      </li>
      <li>Use the Service in violation of any applicable law.</li>
    </ul>

    <h2>Intellectual Property</h2>
    <p>
      The Service and its content — including practice questions,
      explanations, diagnostic text, software, and design — are owned by
      [LEGAL ENTITY NAME] or its licensors and are protected by copyright
      and other intellectual-property laws. We grant you a limited,
      personal, non-exclusive, non-transferable license to use the Service
      for your own SAT preparation. You retain ownership of the information
      you submit (such as your study profile); you grant us the rights
      needed to operate the Service with it, as described in the Privacy
      Policy.
    </p>
    <p>
      SAT is a registered trademark of the College Board, which is not
      affiliated with and does not endorse this product.
    </p>

    <h2>AI-Generated Content</h2>
    <p>
      The AI tutor and certain explanations are generated by artificial
      intelligence. AI-generated content can be incomplete or incorrect.
      It is provided for study purposes only and should not be treated as
      authoritative; verify important information independently. We are not
      responsible for decisions you make in reliance on AI-generated
      output.
    </p>

    <h2>Disclaimer of Warranties</h2>
    <p>
      The Service is provided "as is" and "as available", without
      warranties of any kind, whether express or implied, including implied
      warranties of merchantability, fitness for a particular purpose, and
      non-infringement. We do not warrant that the Service will be
      uninterrupted, error-free, or that practice results will predict your
      actual SAT score.
    </p>

    <h2>Limitation of Liability</h2>
    <p>
      To the maximum extent permitted by law, [LEGAL ENTITY NAME] will not
      be liable for any indirect, incidental, special, consequential, or
      punitive damages, or for lost profits, data, or goodwill, arising
      from or related to your use of the Service. To the maximum extent
      permitted by law, our total liability for any claim arising out of
      these Terms or the Service will not exceed the greater of the amount
      you paid us for the Service in the twelve months before the claim
      arose or one hundred US dollars (USD 100). Some jurisdictions do not
      allow certain limitations, so parts of this section may not apply to
      you.
    </p>

    <h2>Termination</h2>
    <p>
      You may stop using the Service and request deletion of your account
      at any time. We may suspend or terminate your access if you violate
      these Terms, if required by law, or if we discontinue the Service.
      Sections that by their nature should survive termination (including
      Intellectual Property, Disclaimer of Warranties, and Limitation of
      Liability) survive.
    </p>

    <h2>Changes to These Terms</h2>
    <p>
      We may update these Terms from time to time. If we make material
      changes, we will update the date at the top of this page and, where
      appropriate, notify you in the app before the changes take effect.
      Continuing to use the Service after changes take effect means you
      accept the updated Terms.
    </p>

    <h2>Governing Law</h2>
    <p>
      These Terms are governed by the laws of [GOVERNING JURISDICTION],
      without regard to its conflict-of-laws rules. Any dispute arising
      from these Terms or the Service will be resolved in the courts of
      [GOVERNING JURISDICTION], unless applicable law gives you the right
      to a different forum.
    </p>

    <h2>Contact</h2>
    <p>
      Questions about these Terms can be sent to [LEGAL ENTITY NAME] at
      [CONTACT EMAIL].
    </p>
  </LegalPageLayout>
);

export default TermsOfService;
